# Generated by Django 4.2.4 on 2023-09-02 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_assigner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigner',
            new_name='assignee',
        ),
    ]
